// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtRtEYkXQvEylOcFc622VCfd_jUHl1cUY',
    appId: '1:721499801239:web:236b2ef8552408cc6a4bd2',
    messagingSenderId: '721499801239',
    projectId: 'arganicz',
    authDomain: 'arganicz.firebaseapp.com',
    storageBucket: 'arganicz.firebasestorage.app',
    measurementId: 'G-3C3Z8HH3RW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmjDVCCIzOD6ZtR5WhsH-AKJjoRCiJ0-E',
    appId: '1:721499801239:android:ae840c9858cbf6056a4bd2',
    messagingSenderId: '721499801239',
    projectId: 'arganicz',
    storageBucket: 'arganicz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbSEENvNDUmk62uqITWgzSAcxPVSk1T0A',
    appId: '1:721499801239:ios:75f18bddcf7ea2e36a4bd2',
    messagingSenderId: '721499801239',
    projectId: 'arganicz',
    storageBucket: 'arganicz.firebasestorage.app',
    androidClientId: '721499801239-c4l39op9m61qio776hmal20gv3uqf7h5.apps.googleusercontent.com',
    iosClientId: '721499801239-o4kl9a3us7b45kjbhum5ufolrg2eikbj.apps.googleusercontent.com',
    iosBundleId: 'com.arganicz.userapps',
  );
}
